### ISSUE TITLE
Remove all uses of text-transform: uppercase

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3943]
The `text-transform: uppercase` CSS rule removes control over case from translators. Some languages may not want to show all-caps for a variety of reasons, e.g. stylistic conventions, or because the fonts we use don't correctly support diacritics on uppercase characters.

Instead, we should use separate translation strings for all-caps strings. I tend to append `_caps` to these strings, e.g. 

```yaml
an_important_title: An Important Title
an_important_title_caps: AN IMPORTANT_TITLE
an_important_title_html: <h1>An Important Title</h1>
an_important_title_caps_html: <h1>AN IMPORTANT TITLE</h1>
```

It would be really great if we could have some linting rule to prevent the use of `text-transform: uppercase`, but I don't think we have any CSS linting yet.
